# Generated by Django 2.1.5 on 2019-02-22 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='artist',
            new_name='about_me',
        ),
    ]
