# Generated by Django 2.1.5 on 2019-02-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190223_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutme',
            name='about_me',
            field=models.CharField(max_length=2000),
        ),
    ]
