# Generated by Django 2.1.5 on 2019-02-23 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20190223_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=100)),
                ('offered_by', models.CharField(max_length=100)),
                ('plateform', models.CharField(max_length=50)),
                ('score', models.IntegerField(blank=True)),
                ('certificate_link', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=100)),
                ('s_description', models.CharField(max_length=250)),
                ('l_description', models.CharField(max_length=100)),
                ('highlight_1', models.CharField(max_length=250)),
                ('highlight_2', models.CharField(max_length=250)),
                ('highlight_3', models.CharField(max_length=250)),
            ],
        ),
    ]
