# Generated by Django 2.1.5 on 2019-02-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_course_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='l_description',
            field=models.CharField(max_length=1000),
        ),
    ]
