# Generated by Django 2.1.5 on 2019-02-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20190223_0723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutMe',
        ),
    ]
