# Generated by Django 2.1.5 on 2019-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_computerskills_education_hackathon_hobbies_possitionsofresponsibility_professtionalintrests_voluntee'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerexperience',
            name='role1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='volunteerexperience',
            name='role2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='volunteerexperience',
            name='role3',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
